### ISSUE TITLE
Roll back the anti-bridge.

### ISSUE THREAD

**Issue by MikeDev101** [mybearworld/roarer-2#15]
CC: https://github.com/mybearworld/roarer/issues/4#issue-2370952259

**Comment by mybearworld** [comment]
I do not see this feature as needless nor arbitrary, as the Discord bridge is used often and is thereby actively stopping Meower from improving — as an example of this, it's often used for its post searching mechanism, instead of Meower's built in mechanism being used and improved. 

Additionally, Roarer does not do anything that could not realistically be done by a human to achieve this — it simply automates an action that any user could do by hand.

**Comment by NotFenixio** [comment]
If people want to use Discord, they should use Discord then. There's no need on legally threatening someone because a client with no connection to Meower Media (this whole thing is ridiculous since it's not like mybearworld or roarer are attached or have some kind of contract going around with it) does an annoying thing to a bunch of users. The Discord bridge is an awful experience anyways. 😕.

P.D.: Your own ToS says it! "Nobody likes lawsuits"!

**Comment by JoshAtticus** [comment]
Tnix is modifying bridge to stop this roarer bug
